### ISSUE TITLE
can not creat account

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/www-mastodon#154]
when using create account it gives an error
![image](https://user-images.githubusercontent.com/110984055/236813477-5d8cc084-3d6c-42f0-85db-e992b4688c29.png)

steps to produce :

1. go to mastodon
2. click on create account

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/www-mastodon/pull/162

**Comment by khaledyoussef24** [comment]
still exists but with a new error
![image](https://github.com/threefoldtech/www-mastodon/assets/110984055/f1ac4215-2d98-491f-aebd-c3e5e4aa0855)

**Comment by Mahmoud-Emad** [comment]
I just tested it and it worked quite well.

[Screencast from 28-05-23 08:04:42.webm](https://github.com/threefoldtech/www-mastodon/assets/57001890/298f2d69-b966-4a23-bd99-6d283b0418ba)

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/

Account creations is working.

![image](https://github.com/threefoldtech/www-mastodon/assets/101194226/5da6184c-348e-4a2f-9351-206f10062dc1)

And when i imported the seed in polkadot i was able to check the account details from the dashboard and the twin, relay were set up correctly.

![image](https://github.com/threefoldtech/www-mastodon/assets/101194226/585d529d-b2fc-4cbd-a3a5-0a057708a7e0)
