### ISSUE TITLE
Up and running still waiting on the deployed instance after the deployed instance was deleted!

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/www-mastodon#66]
Deployed an instance then I refreshed the page to deploy another one to test the new deletion feature added then I selected all my instances to delete, then all my instances were deleted, and up and running still appear and listening on the deleted node. 

### Steps to verify 
* Deploy the first instance
![image](https://user-images.githubusercontent.com/57001890/205492680-16748cf0-d369-44d7-bdf1-a31932523d0b.png)

* Deploy the second instance
![image](https://user-images.githubusercontent.com/57001890/205492726-46f46e9a-a8e7-4b8b-988b-415073de970b.png)

* Refresh the page 
* Watch the hint message `Waiting for your mastodon instance to be up and running...`
![image](https://user-images.githubusercontent.com/57001890/205492750-4a295bcc-6b1c-4d76-bcde-836d6aca7b80.png)

* Select all deployed instances then confirm delete them 
![image](https://user-images.githubusercontent.com/57001890/205492870-f857e2f7-419b-46eb-9058-be133e6453b0.png)
![image](https://user-images.githubusercontent.com/57001890/205493045-732723af-18f8-47d3-b18b-9d21a5a8e295.png)

* after deletion watch the hint message again

![image](https://user-images.githubusercontent.com/57001890/205494171-c8a96ecf-ddab-4cc0-a889-5f13a51d4d1d.png)

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/www-mastodon/pull/70

**Comment by mohamedamer453** [comment]
I followed the same flow mentioned above and the issue is still there. firstly i deployed an instance then i deployed the second. after the second instance was deployed and the `Waiting for your mastodon instance to be up and running...` message appeared i reloaded the deployment list then i deleted both instances, but after deleting the instance the message did not go away and i was unable to use the `Back` button even though the instance that i'm supposed to be waiting for was deleted.

[Get Mastodon (24).webm](https://user-images.githubusercontent.com/101194226/206173956-555b1b42-3084-47a8-bac1-869483de23b9.webm)

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/www-mastodon/pull/114 the reload button is disabled until the instance running

**Comment by mohamedamer453** [comment]
Verified on https://getmastodon.threefold.io/
The issue was fixed and the `Reload` button is now disabled until the deployment is ready.

[Get Mastodon (34).webm](https://user-images.githubusercontent.com/101194226/208289629-b40108e7-1c3b-43b1-bbeb-e0bc1776ca4b.webm)
